import telebot
from pytube import YouTube

# Change the 'TOKEN' (GENERATED BY BOT FATHER)
TOKEN = 'TOKEN'
bot = telebot.TeleBot(TOKEN)

@bot.message_handler(commands=['start'])
def send_welcome(message):
    bot.reply_to(message, "Welcome to EFX TV YouTube Downloader Bot!\nSend me a YouTube link and I'll download the video for you. Cheers")

@bot.message_handler(func=lambda message: True)
def download_video(message):
    try:
        youtube_url = message.text
        yt = YouTube(youtube_url)
        stream = yt.streams.filter(progressive=True, file_extension='mp4').first()
        video_file = stream.download()
        with open(video_file, 'rb') as video:
            bot.send_video(message.chat.id, video)
    except Exception as e:
        bot.reply_to(message, f"An error occurred: {str(e)}")

bot.polling()
